### ISSUE TITLE
Change items of info screen

### ISSUE THREAD

**Issue by rgonzaleztec** [rgonzaleztec/aspcglab#5]
We need to change this:

- Cambiar a País de procedencia por nacionalidad
- Lista de paises para con acronimos o algo similar para evitar que la persona escriba y genere datos que se tengan que limpiar
- Año de Nacimiento para identificar lo de la edad

**Comment by jochaes** [comment]
![image](https://github.com/rgonzaleztec/aspcglab/assets/17283862/a66e4441-a48b-42c0-b34d-279cf8320dde)
